name: ci

# Run this workflow every time a new commit / pull request pushed to master
# branh
on:
  push:
    branches: [ dev ]
  pull_request:
    # TODO: add `dev` branch later
    branches: [ main ]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  ci:
    # Name the Job
    name: Build and run test
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: apt update
        run: sudo apt update
      - name: apt install build-essential cmake
        run: sudo apt install -y build-essential cmake
      - name: Build and run test
        run: make ci
